# Generated by Django 3.2.16 on 2023-12-04 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('foodgram', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingridients',
            options={'verbose_name_plural': 'RecipeIngridients'},
        ),
        migrations.AlterField(
            model_name='recipeingridients',
            name='ingredients',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='foodgram.ingridient',
                verbose_name='Ингредиенты',
            ),
        ),
    ]
